-- Supabase schema for storing pinned Instagram posts
-- Run this in the Supabase SQL editor for your project

create table if not exists public.portfolio_instagram_pins (
  id bigint generated by default as identity primary key,
  post_id text not null unique,
  pinned_at timestamptz not null default now(),
  active boolean not null default true
);

-- Optional index for quick lookup of active pin
create index if not exists idx_portfolio_instagram_pins_active on public.portfolio_instagram_pins (active desc, pinned_at desc);
